Add debug in TileEntityFancySkullRenderer
to debug :

```
com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.mojang.authlib.minecraft.MinecraftProfileTexture.<init>(Ljava/lang/String;Ljava/lang/String;)V
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at net.minecraft.client.resources.SkinManager.func_152788_a(SkinManager.java:204)
	at ganymedes01.etfuturum.client.renderer.tileentity.TileEntityFancySkullRenderer.renderSkull(TileEntityFancySkullRenderer.java:61)
	at ganymedes01.etfuturum.client.renderer.item.ItemSkullRenderer.renderSkull(ItemSkullRenderer.java:53)
	at ganymedes01.etfuturum.client.renderer.item.ItemSkullRenderer.renderItem(ItemSkullRenderer.java:33)
	at net.minecraftforge.client.ForgeHooksClient.renderEntityItem(ForgeHooksClient.java:136)
	at net.minecraft.client.renderer.entity.RenderItem.func_76986_a(RenderItem.java:93)
	at net.minecraft.client.renderer.entity.RenderItem.func_76986_a(RenderItem.java:746)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:8006)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: com.mojang.authlib.minecraft.MinecraftProfileTexture.<init>(Ljava/lang/String;Ljava/lang/String;)V
	at by.ely.authlib.ElyTextureService.ofTexture(ElyTextureService.java:307)
	at by.ely.authlib.ElyTextureService.getElyTextureOffline(ElyTextureService.java:171)
	at by.ely.authlib.ElyTextureService.getElyTexture(ElyTextureService.java:140)
	at by.ely.authlib.ElyTextureService.getTextureMap(ElyTextureService.java:82)
	at by.ely.authlib.ElyTextureService.getTextures(ElyTextureService.java:61)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:169)
	at net.minecraft.client.resources.SkinManager$1.func_152786_a(SkinManager.java:55)
	at net.minecraft.client.resources.SkinManager$1.load(SkinManager.java:59)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 26 more